In [ ]:
Cell 1: Title

# Name: Your Name
# Student ID: Your ID

# SQL and Pandas Data Analysis: Employee Database

In [1]:
import sqlite3
import random
import pandas as pd

# Connect to database (creates file if not exists)
conn = sqlite3.connect("employees.db")
cursor = conn.cursor()

# Create table
cursor.execute("""
CREATE TABLE IF NOT EXISTS employees (
    emp_id INTEGER PRIMARY KEY,
    name TEXT,
    department TEXT,
    salary REAL,
    years_experience INTEGER,
    performance_score REAL
)
""")

# Departments list
departments = ["Engineering", "Sales", "Marketing", "HR", "Finance"]

# Insert synthetic data (40+ records)
data = []
for i in range(1, 51):  # 50 records
    name = f"Employee_{i}"
    dept = random.choice(departments)
    salary = random.randint(50000, 150000)
    exp = random.randint(1, 15)
    score = round(random.uniform(1.0, 5.0), 2)

    data.append((i, name, dept, salary, exp, score))

cursor.executemany("""
INSERT INTO employees (emp_id, name, department, salary, years_experience, performance_score)
VALUES (?, ?, ?, ?, ?, ?)
""", data)

conn.commit()

print("Database created and data inserted successfully!")

Database created and data inserted successfully!

Task 2: SQL Queries

Query 1

In [2]:
query1 = """
SELECT name, department, salary, performance_score
FROM employees
WHERE performance_score >= 4.0 AND years_experience >= 3
ORDER BY performance_score DESC
LIMIT 15
"""

df_q1 = pd.read_sql_query(query1, conn)
df_q1

           name department    salary  performance_score
0    Employee_9         HR   66751.0               4.87
1   Employee_12  Marketing  107826.0               4.76
2   Employee_28         HR   91086.0               4.76
3   Employee_26      Sales   63350.0               4.74
4   Employee_24    Finance  148647.0               4.60
5    Employee_6  Marketing  108621.0               4.46
6    Employee_4         HR   64848.0               4.38
7    Employee_1    Finance   59649.0               4.31
8    Employee_7  Marketing   94494.0               4.31
9   Employee_34      Sales  122603.0               4.29
10  Employee_41    Finance   86050.0               4.00

Query 2

In [3]:
query2 = """
SELECT *
FROM employees
WHERE salary BETWEEN 70000 AND 110000
AND (department = 'Engineering' OR department = 'Sales')
ORDER BY department, salary DESC
"""

df_q2 = pd.read_sql_query(query2, conn)
df_q2

,emp_id,name,department,salary,years_experience,performance_score
0,15,Employee_15,Engineering,83576.0,9,3.41
1,38,Employee_38,Engineering,75824.0,7,3.45
2,5,Employee_5,Sales,100232.0,1,2.01
3,36,Employee_36,Sales,90022.0,9,1.94
4,43,Employee_43,Sales,84016.0,5,1.88
5,22,Employee_22,Sales,83195.0,11,3.51
6,16,Employee_16,Sales,79092.0,9,2.86
7,49,Employee_49,Sales,76818.0,3,3.74

Query 3

In [4]:
query3 = """
SELECT department, COUNT(*) AS employee_count, AVG(salary) AS avg_salary
FROM employees
GROUP BY department
ORDER BY avg_salary DESC
"""

df_q3 = pd.read_sql_query(query3, conn)
df_q3

    department  employee_count     avg_salary
0    Marketing              11  107748.818182
1  Engineering               4  106281.250000
2        Sales              12  101733.250000
3           HR              16   95795.250000
4      Finance               7   77388.285714

Task 3: Pandas Analysis

Average Performance Score by Department

In [5]:
df_all = pd.read_sql_query("SELECT * FROM employees", conn)

avg_perf = df_all.groupby("department")["performance_score"].mean()
avg_perf

department
Engineering    3.197500
Finance        3.102857
HR             2.996250
Marketing      2.990909
Sales          2.919167
Name: performance_score, dtype: float64

Replicate Query 1 using Pandas ONLY

In [6]:
df_pandas_q1 = (
    df_all.loc[
        (df_all["performance_score"] >= 4.0) &
        (df_all["years_experience"] >= 3),
        ["name", "department", "salary", "performance_score"]
    ]
    .sort_values(by="performance_score", ascending=False)
    .head(15)
)

df_pandas_q1

           name department    salary  performance_score
8    Employee_9         HR   66751.0               4.87
11  Employee_12  Marketing  107826.0               4.76
27  Employee_28         HR   91086.0               4.76
25  Employee_26      Sales   63350.0               4.74
23  Employee_24    Finance  148647.0               4.60
5    Employee_6  Marketing  108621.0               4.46
3    Employee_4         HR   64848.0               4.38
0    Employee_1    Finance   59649.0               4.31
6    Employee_7  Marketing   94494.0               4.31
33  Employee_34      Sales  122603.0               4.29
40  Employee_41    Finance   86050.0               4.00

Task 4: Comparison (Markdown Cell)

In [8]:
text = """
SQL and Pandas are both powerful tools for data analysis but differ in syntax and use cases. SQL uses operators like =, AND, and ORDER BY for filtering and sorting, whereas Pandas uses ==, &, and methods like .sort_values(). SQL queries are declarative, meaning you specify what you want, while Pandas is more procedural, where you define step-by-step operations.

SQL is best suited for working with structured data stored in databases, especially when handling large datasets. It efficiently processes data directly on the database server without loading everything into memory. On the other hand, Pandas is ideal for in-memory data analysis, offering flexibility, advanced transformations, and integration with Python libraries.

For datasets too large to fit into memory, SQL is the better choice because it performs operations within the database engine, avoiding memory limitations. Pandas may struggle in such cases as it requires loading data into RAM.

In summary, SQL is preferred for large-scale data querying, while Pandas is better for detailed analysis and data manipulation.
"""

print(text)

SQL and Pandas are both powerful tools for data analysis but differ in syntax and use cases. SQL uses operators like =, AND, and ORDER BY for filtering and sorting, whereas Pandas uses ==, &, and methods like .sort_values(). SQL queries are declarative, meaning you specify what you want, while Pandas is more procedural, where you define step-by-step operations.

SQL is best suited for working with structured data stored in databases, especially when handling large datasets. It efficiently processes data directly on the database server without loading everything into memory. On the other hand, Pandas is ideal for in-memory data analysis, offering flexibility, advanced transformations, and integration with Python libraries.

For datasets too large to fit into memory, SQL is the better choice because it performs operations within the database engine, avoiding memory limitations. Pandas may struggle in such cases as it requires loading data into RAM.

In summary, SQL is preferred for large-scale data querying, while Pandas is better for detailed analysis and data manipulation.

(Optional) Close Connection

In [10]:
conn.close()